---
# file: roles/rosa-build/tasks/git.yml


- name: git | set user.name
  command: git config --global user.name {{ git.name }}

- name: git | set user.email
  command: git config --global user.email {{ git.email }}

- name: git | core.quotepath
  command: git config --global core.quotepath false

- name: create user git
  user: state=present name=git createhome=yes shell=/bin/bash generate_ssh_key=yes

# TODO
