---
# file: roles/rosa-build/tasks/gitlab_shell.yml

- name: appending the group 'git' to the {{ user }}'s groups
  command: sudo usermod -a -G git rosa

- name: appending the group '{{ user }}' to the git's groups
  command: sudo usermod -a -G rosa git

- name: gitlab_shell | clone repo
  remote_user: root
  git: >
    repo={{ gitlab_shell.repo }}
    version={{ gitlab_shell.branch }}
    dest=/home/git/gitlab-shell
    update=true force=true
  environment:
    GIT_SSL_NO_VERIFY: true

- name: gitlab_shell | creates config.yml
  remote_user: root
  template: src=gitlab_shell/config.yml dest=/home/git/gitlab-shell/config.yml
