---
# file: abf-worker.yml

- hosts: abf-worker
  user: root
  roles:
    - common
  vars:
    user: root

- name: manage application user
  hosts: abf-worker
  user: root
  roles:
    - user
  vars:
    user: rosa

- name: setup rvm, ruby, gemset and etc.
  hosts: abf-worker
  remote_user: rosa
  roles:
    - ruby
    - abf-worker
  vars:
    ruby_version: 2.1.1
    deploy_to: /home/rosa/abf-worker
    store_path: /mnt/store
    user: rosa
    repo: https://abf.io/abf/abf-worker-lxc.git
    repo_with_auth: https://abf:abf@abf.io/abf/abf-worker-lxc.git
    branch: master

- name: deploy abf-worker-rpm
  hosts: abf-worker-rpm
  remote_user: rosa
  roles:
    - abf-worker-deploy
  vars:
    ruby_version: 2.1.1
    deploy_to: /home/rosa/abf-worker
    user: rosa
    worker_type: rpm

- name: deploy abf-worker-iso
  hosts: abf-worker-iso
  remote_user: rosa
  roles:
    - abf-worker-deploy
  vars:
    ruby_version: 2.1.1
    deploy_to: /home/rosa/abf-worker
    user: rosa
    worker_type: iso

- name: deploy abf-worker-publish
  hosts: abf-worker-publish
  remote_user: rosa
  roles:
    - abf-worker-deploy
  vars:
    ruby_version: 2.1.1
    deploy_to: /home/rosa/abf-worker
    user: rosa
    worker_type: publish

