---
# file: abf-downloads.yml

- hosts: abf-downloads
  user: root
  roles:
    - common
  vars:
    user: root

- name: manage application user, configure abf-downloads
  hosts: abf-downloads
  user: root
  roles:
    - user
    - abf-downloads
  vars:
    user: rosa
    share_platforms: /share/platforms
