---
# file: abf-worker.yml

- hosts: abf-worker
  user: root
  roles:
    - common

- name: manage application user
  hosts: abf-worker
  user: root
  roles:
    - user

- name: setup rvm, ruby, gemset and etc.
  hosts: abf-worker
  remote_user: rosa
  roles:
    - ruby
    - abf-worker
  vars:
    ruby_version: 2.1.1
    platform_name: rosa-server65
