---
# file: abf-worker.yml

- hosts: abf-worker
  user: root
  roles:
    - common

- name: manage application user
  hosts: abf-worker
  user: root
  roles:
    - user
  vars:
    user: rosa

- name: setup rvm, ruby, gemset and etc.
  hosts: abf-worker
  remote_user: rosa
  roles:
    - ruby
    - abf-worker
  vars:
    ruby_version: 2.1.1
    deploy_to: /home/rosa/abf-worker
    store_path: /mnt/store
    user: rosa
    repo: https://abf.io/abf/abf-worker-lxc.git
    branch: master

- name: deploy abf-worker-rpm
  hosts: abf-worker-rpm
  remote_user: rosa
  roles:
    - abf-worker-rpm
  vars:
    ruby_version: 2.1.1
    deploy_to: /home/rosa/abf-worker
