---
# file: rosa-build.yml

- hosts: rosa-build
  user: root
  roles:
    - common

- name: manage application user
  hosts: rosa-build
  user: root
  roles:
    - user
  vars:
    user: rosa

- name: manage application user
  hosts: rosa-build
  user: root
  roles:
    - user
  vars:
    user: git
    skip_config_sudoers: true

- name: Install PostgreSQL
  hosts: rosa-build
  user: root
  roles:
    - PostgreSQL
  vars:
    # Basic settings
    postgresql_version: 9.3
    postgresql_encoding: 'UTF-8'
    postgresql_locale: 'en_US.UTF-8'

    postgresql_admin_user: postgres
    postgresql_default_auth_method: trust

    # postgresql_cluster_name: "main"
    postgresql_cluster_name: "data"
    postgresql_cluster_reset: false

    # List of databases to be created (optional)
    postgresql_databases:
      - name: rosa_build
        # flag to install the hstore extensions on this database (yes/no)
        hstore: 'yes'

    # List of users to be created (optional)
    postgresql_users:
      - name: rosa
        pass:
        # denotes if the password is already encrypted.
        encrypted: no

    # List of user privileges to be applied (optional)
    postgresql_user_privileges:
      # user name
      - name: rosa
        # database
        db: rosa_build
        # privilege string format: example: INSERT,UPDATE/table:SELECT/anothertable:ALL
        priv: ALL

- name: setup rvm, ruby, gemset and etc. for git user
  hosts: rosa-build
  remote_user: rosa
  roles:
    - ruby
  vars:
    ruby_version: 1.9.3-p392

- name: setup rvm, ruby, gemset and etc., deploy
  hosts: rosa-build
  remote_user: rosa
  roles:
    - ruby
    - rosa-build
  vars:
    ruby_version: 2.1.1
    deploy_to: /srv/rosa_build
    user: rosa
    repo: https://abf.io/abf/rosa-build.git
    # branch: master
    branch: abf-ansible

    git:
      name: Rosa
      email: rosa@abf.io

    gitlab_shell:
      repo: https://abf.io/abf/gitlab-shell.git
      branch: master

    nginx:
      # use_ssl - true/false
      use_ssl: false
      ssl_certificate: /etc/ssl/abf.crt
      ssl_certificate_key: /etc/ssl/abf.key

    application:
      action_mailer_host: 'abf.io'
      tmpfs_path: '/dev/shm'
      root_path: '/share'
      git_path: '/mnt/gitstore'
      nginx_log: '/srv/rosa_build/shared/log/nginx.access.log'
      do_not_reply_email: 'do-not-reply@rosalinux.ru'
      file_store_url: 'http://file-store.rosalinux.ru'
      downloads_url: 'http://abf-downloads.rosalinux.ru/'
      feedback:
        email:
          - 'abf-support@rosalab.ru'
        cc:
          - 'example@gmail.com'
      github_services:
        ip: '127.0.0.1'
        port: 4000
      allowed_addresses:
        - 127.0.0.1
      abf_worker:
        publish_workers_count: 4
        log_server:
          host: '127.0.0.1'
          port: '6379'

