---
# file: roles/abf-downloads/tasks/nginx.yml

- name: add abf-worker-service repo
  copy: >
    src=rosa-server65/abf-worker-service.repo
    dest=/etc/yum.repos.d/abf-worker-service.repo
    owner=root group=root mode=0644
  when: platform_name is defined and platform_name == "rosa-server65"

- name: add the centOS 6.5 nginx yum repository
  command: sudo rpm -Uvh http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
  ignore_errors: true
  when: platform_name is defined and platform_name == "centos6.5"

- name: disable selinux on centos
  lineinfile: >
    dest=/etc/sysconfig/selinux
    regexp="^SELINUX="
    line="SELINUX=disabled"
  register: need_restart_server
  when: platform_name is defined and platform_name == "centos6.5"

- debug: var=need_restart_server.changed

# See: https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back
- name: restart machine
  command: sudo shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: platform_name is defined and platform_name == "centos6.5" and need_restart_server.changed

- debug: var=ansible_ssh_host
- debug: var=ansible_ssh_port

- name: waiting for server to come back
  local_action: >
    wait_for host="{{ ansible_ssh_host }}"
    port={{ ansible_ssh_port }}
    search_regex=OpenSSH
    state=started
    delay=30
  when: platform_name is defined and platform_name == "centos6.5" and need_restart_server.changed

- name: nginx | install useful soft
  yum: pkg={{ item }} state=present
  with_items:
    - nginx

- name: nginx | create nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: nginx | create /etc/nginx/conf.d directory
  file: path=/etc/nginx/conf.d state=directory

- name: nginx | creates abf-downloads.conf
  template: src=abf-downloads.conf dest=/etc/nginx/conf.d/abf-downloads.conf

- name: nginx | restart nginx
  action: service name=nginx state=restarted

- name: autostart nginx
  command: sudo chkconfig --levels 235 nginx on
