---
# file: roles/abf-downloads/tasks/nginx.yml

- name: nginx | install useful soft
  yum: pkg={{ item }} state=present
  with_items:
    - nginx

- name: nginx | create nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: nginx | create /etc/nginx/conf.d directory
  file: path=/etc/nginx/conf.d state=directory

- name: nginx | creates abf-downloads.conf
  template: src=abf-downloads.conf dest=/etc/nginx/conf.d/abf-downloads.conf

- name: nginx | restart nginx
  action: service name=nginx state=restarted
