---
# file: roles/file-store/tasks/nginx.yml

- name: nginx | ensure that no tmp dir for nginx
  file: path=/home/{{ user }}/nginx state=absent
  ignore_errors: yes
  sudo: yes

- name: nginx | create directory
  file: path=/home/{{ user }}/nginx state=directory

- name: nginx | download pcre
  command: >
    wget http://sourceforge.net/projects/pcre/files/pcre/8.35/pcre-8.35.tar.gz/download -O pcre-8.35.tar.gz
    chdir=/home/{{ user }}/nginx

- name: nginx | extract pcre
  command: >
    tar -xf pcre-8.35.tar.gz
    chdir=/home/{{ user }}/nginx

- name: nginx | configure pcre
  command: >
    ./configure
    chdir=/home/{{ user }}/nginx/pcre-8.35

- name: nginx | make pcre
  command: make chdir=/home/{{ user }}/nginx/pcre-8.35

- name: nginx | install pcre
  command: make install chdir=/home/{{ user }}/nginx/pcre-8.35
  sudo: yes

- name: nginx | download nginx
  command: >
    wget http://nginx.org/download/nginx-1.3.8.tar.gz
    chdir=/home/{{ user }}/nginx

- name: nginx | extract nginx
  command: >
    tar -xf nginx-1.3.8.tar.gz
    chdir=/home/{{ user }}/nginx

- name: nginx | rename nginx folder
  command: >
    mv nginx-1.3.8 nginx
    chdir=/home/{{ user }}/nginx

- name: nginx | download nginx-upload-progress-module
  command: >
    wget https://github.com/masterzen/nginx-upload-progress-module/archive/v0.9.1.tar.gz -O nginx-upload-progress-module.tar.gz
    chdir=/home/{{ user }}/nginx

- name: nginx | extract nginx-upload-progress-module
  command: >
    tar -xf nginx-upload-progress-module.tar.gz
    chdir=/home/{{ user }}/nginx

- name: nginx | rename nginx-upload-progress-module folder
  command: >
    mv nginx-upload-progress-module-0.9.1 nginx-upload-progress-module
    chdir=/home/{{ user }}/nginx

- name: nginx | download nginx_upload_module
  command: >
    wget http://www.grid.net.ru/nginx/download/nginx_upload_module-2.2.0.tar.gz -O nginx_upload_module.tar.gz
    chdir=/home/{{ user }}/nginx

- name: nginx | extract nginx_upload_module
  command: >
    tar -xf nginx_upload_module.tar.gz
    chdir=/home/{{ user }}/nginx

- name: Rename nginx_upload_module folder
  command: >
    mv nginx_upload_module-2.2.0 nginx_upload_module
    chdir=/home/{{ user }}/nginx

- name: nginx | configure nginx
  command: >
    ./configure --prefix=/usr/share/nginx
    --sbin-path=/usr/sbin/nginx
    --conf-path=/etc/nginx/nginx.conf
    --error-log-path=/var/log/nginx/error.log
    --http-log-path=/var/log/nginx/access.log
    --with-http_flv_module
    --with-http_ssl_module
    --with-http_gzip_static_module
    --add-module=/home/{{ user }}/nginx/nginx_upload_module
    --add-module=/home/{{ user }}/nginx/nginx-upload-progress-module
    chdir=/home/{{ user }}/nginx/nginx

- name: nginx | make nginx
  command: make chdir=/home/{{ user }}/nginx/nginx

- name: nginx | install nginx
  command: make install chdir=/home/{{ user }}/nginx/nginx
  sudo: yes

# fix nginx: error while loading shared libraries:
# libpcre.so.1: cannot open shared object file: No such file or directory
- name: nginx | create link to /usr/local/lib/libpcre.so.1
  sudo: yes
  command: ln -s /usr/local/lib/libpcre.so.1 /lib64
  ignore_errors: yes
