common: &common
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: 5
  timeout: 5000

production:
  <<: *common
  username: {{ user }}
  password: {{ user }}
  database: rosa_file_store
