---

- name: mdv | add the MDV repo
  command: urpmi.addmedia main_release http://abf-downloads.rosalinux.ru/rosa2014.1/repository/x86_64/main/release/
  when: platform_name == "rosa2014.1"
  ignore_errors: true

- name: mdv | install useful soft
  urpmi: pkg={{ item }} state=present
  with_items:
    - git
    - curl
    - patch
    - tar
