---

- name: install useful soft
  yum: pkg={{ item }} state=present
  with_items:
    - git
    - curl
    - patch
    - tar
    - libselinux-python # need for lineinfile module

    # TODO fix install this packages
    #- bsdtar
    #- redir
