- name: rhel | lxc_setup | enable IPv4 forwarding
  lineinfile: >
    dest=/etc/hosts
    regexp='^net.ipv4.ip_forward = 0$'
    line='net.ipv4.ip_forward = 1'
  sudo: yes
  register: restart_sysctl

- name: rhel | lxc_setup | restart sysctl
  command: sudo sysctl -p
  when: restart_sysctl|success

- name: rhel | lxc_setup | start/enable libvirtd service
  service: name=libvirtd state=started enabled=yes
  sudo: true
